
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerId: luoyunchong@foxmail.com            
  namespace: igeekfan                            
  identityserver4imageName: lincms-identityserver4      
  webimageName: lincms-web      
  registry: registry.cn-hangzhou.aliyuncs.com
  identityserver4dockerfilepath:  identityserver4/LinCms.IdentityServer4/Dockerfile 
  linCmsWebdockerfilepath:  src/LinCms.Web/Dockerfile  

steps:
- task: CmdLine@2
  inputs:
    script: |
      echo read to execute command
      ls
      sed -i 's/{ConnectionStrings.Default}/$(ConnectionStrings.Default)/g' identityserver4/LinCms.IdentityServer4/appsettings.Production.json
      echo command executed

- script: |
    docker build -f $(identityserver4dockerfilepath) -t $(identityserver4imageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(identityserver4imageName) $(registry)/$(namespace)/$(identityserver4imageName)
    docker push $(registry)/$(namespace)/$(identityserver4imageName)

  displayName: push to lincms-identityserver4

- script: |
    docker build -f $(linCmsWebdockerfilepath) -t $(webimageName) .
    docker login -u $(dockerId) -p $(pwd) $(registry)
    docker tag $(webimageName) $(registry)/$(namespace)/$(webimageName)
    docker push $(registry)/$(namespace)/$(webimageName)

  displayName: push to lincms-web